export const icons = {
  add: "/icons/add.png",
  addTag: "/icons/add-tag.png",
  addWhite: "/icons/add-white.png",
  back: "/icons/back.png",
  badge: "/icons/badge.png",
  bell: "/icons/bell.png",
  bellActive: "/icons/bell-active.png",
  camera: "/icons/camera.png",
  cameraGrey: "/icons/camera-grey.png",
  checkin: "/icons/checkin.png",
  checkinTab: "/icons/checkin-tab.png",
  dummy: "/icons/dummy.png",
  editProfile: "/icons/edit-profile.png",
  expand: "/icons/expand.png",
  flagGrey: "/icons/flag-grey.png",
  flag: "/icons/flag.png",
  heart: "/icons/heart.png",
  heartFilled: "/icons/heart-filled.png",
  homeGrey: "/icons/home-grey.png",
  home: "/icons/home.png",
  like: "/icons/like.png",
  likeGrey: "/icons/like-grey.png",
  likeActive: "/icons/like-active.png",
  list: "/icons/list.png",
  menu: "/icons/menu.png",
  message: "/icons/message.png",
  more: "/icons/more.png",
  moreVertical: "/icons/more-vertical.png",
  searchGrey: "/icons/search-grey.png",
  searchTab: "/icons/search-tab.png",
  search: "/icons/search.png",
  ticket: "/icons/ticket.png",
  userGrey: "/icons/user-grey.png",
  user: "/icons/user.png",
};

export type IconTypes = keyof typeof icons;
